component: layer
name: pkuphysu-wechat-python
app: pkuphysu-wechat
stage: ${env:STAGE}
inputs:
  region: ap-shanghai
  zone: ap-shanghai-2
  src:
    src: /opt
    exclude:
      - '**/test'
      - '**/config-3.9-x86_64-linux-gnu'
      - '**/site-packages'
  runtimes:
    - CustomRuntime
