name: Deploy Python Layer

on:
  push:
    branches:
      - master
      - dev
    paths:
      - python/serverless.yml
      - .github/workflows/python-deploy.yml

jobs:
  deploy:
    name: deploy python layer
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip-deploy]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Python layer for the target runtime
        run: |
          mkdir -p python-layer

          docker run --rm \
            -v "${PWD}/python-layer:/opt" \
            -e VERSION=3.9.5 \
            centos:7.7.1908 \
            bash -c '
              sed -i \
                -e "s|^mirrorlist=|#mirrorlist=|g" \
                -e "s|^#baseurl=http://mirror.centos.org/centos/\$releasever|baseurl=http://vault.centos.org/7.9.2009|g" \
                /etc/yum.repos.d/CentOS-*.repo &&
              yum install -y yum-utils make gcc gcc-c++ wget tar \
                bzip2-devel libffi-devel openssl-devel readline-devel \
                sqlite-devel tk-devel xz-devel zlib-devel &&
              wget https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz &&
              tar zxfv Python-$VERSION.tgz &&
              cd Python-$VERSION &&
              ./configure --prefix=/opt/python &&
              make -j"$(nproc)" &&
              make altinstall
            '
      - name: Pre-compile
        run: |
          python-layer/python/bin/python3.9 -c "import sys; print(sys.version)"
          ldd python-layer/python/bin/python3.9 | grep libc
      - name: Determine env
        id: env
        run: |
          if [ $GITHUB_REF == 'refs/heads/master' ]; then
            echo 'stage=prod' >> "$GITHUB_OUTPUT"
          else
            echo 'stage=dev' >> "$GITHUB_OUTPUT"
          fi
      - name: Install serverless
        run: npm install -g serverless-cloud-framework
      - name: Deploy serverless base components
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          # Force deploy to fix permission problem
          scf deploy --force --target python | grep -v -e Initializing -e Uploading -e Deploying -e NA -e password
        env:
          STAGE: ${{ steps.env.outputs.stage }}
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
