name: Deploy Python Layer

on:
  push:
    branches:
      - master
      - dev
    paths:
      - python/serverless.yml

jobs:
  deploy:
    name: deploy python layer
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip-deploy]') }}
    container:
      image: centos:7.7.1908
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install python
        run: |
          mkdir /opt/python
          yum install -y yum-utils make wget
          yum-builddep -y python
          wget https://www.python.org/ftp/python/$VERSION/Python-$VERSION.tgz
          tar zxfv Python-$VERSION.tgz
          cd Python-$VERSION
          ./configure --prefix=/opt/python
          make
          make altinstall
        env:
          VERSION: 3.9.5
      - name: Pre-compile
        run: python -c 'import sys; print(sys.version)'
      - name: Determine env
        id: env
        run: |
          if [ $GITHUB_REF == 'refs/heads/master' ]; then
            echo '::set-output name=stage::prod'
          else
            echo '::set-output name=stage::dev'
          fi
      - name: Install serverless
        run: curl -o- -L https://slss.io/install | bash
      - name: Deploy serverless base components
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          # Force deploy to fix permission problem
          $HOME/.serverless/bin/sls deploy --force | grep -v -e Initializing -e Uploading -e Deploying -e NA -e password
        env:
          STAGE: ${{ steps.env.outputs.stage }}
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
