name: Deploy Serverless Basic

on:
  push:
    branches:
      - master
      - dev
    paths:
      - db/serverless.yml
      - vpc/serverless.yml
      - .github/workflows/sls-deploy.yml

jobs:
  deploy:
    name: deploy serverless
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip-deploy]') }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Determine env
        id: env
        run: |
          if [ $GITHUB_REF == 'refs/heads/master' ]; then
            echo 'stage=prod' >> "$GITHUB_OUTPUT"
          else
            echo 'stage=dev' >> "$GITHUB_OUTPUT"
          fi
      - name: Install serverless
        run: npm install -g serverless-cloud-framework
      - name: Deploy serverless base components
        run: |
          set -o pipefail
          scf deploy --target vpc | grep -v -e '中 ' -e '化 ' -e NA -e password
          scf deploy --target db | grep -v -e '中 ' -e '化 ' -e NA -e password
        env:
          STAGE: ${{ steps.env.outputs.stage }}
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
